#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYz4qR+EHjiUauakIjwCQOCDRAVnEWZSaB8lA9MeG+b5wrAFcTn7okLqoqiYY0JQL3d2JsI1rdy8he+pgxY0/Yl93XdwP00gZMuCtMb/18kxMv/3T1OmcQmIn7N+pEJzkgk8qPSjS3OAGfVzaHtJoh3Eae4R9ZZfH6Fn/Vqs0u/dOpeJdSxbKgvTezR7rr8tsAppMeuOmwR8hrh6tf58P701YfaR33wBKrnXAo/Eo9r68LjnJvo1yCDXMWr7PTyiaD7Ri2L6deUKrkX8RYJ87PVOhCURuAPMCmuegcITK1krnUjLYC/EX01212X9jLkBzC8i4u+bCpiC/wMD+aj5+p
rancher:
    interfaces:
      eth0:
        mtu: 1500
        dhcp: true
    dns:
      nameservers:
        - 10.43.0.10
        - 1.1.1.1
        - 8.8.8.8
      search:

#cloud-config
write_files:
  - content: |+
      #!/bin/bash
      echo "this was a triumph" > /tmp/foo.txt
      # sleep 300
      # iscsiadm ...
    owner: root
    path: /etc/rc.local
    permissions: "0755"
  - path: /etc/ntp.conf
    permissions: "0644"
    owner: root
    content: |
        disable monitor
        restrict default kod nomodify notrap nopeer noquery
        restrict -6 default kod nomodify notrap nopeer noquery
        restrict 127.0.0.1
        restrict -6 ::1
        server ntp.sun.ac.za iburst
        driftfile /var/lib/ntp/drift
  - container: ntp
    path: /etc/ntp.conf
    permissions: "0644"
    owner: root
    content: |
        disable monitor
        restrict default kod nomodify notrap nopeer noquery
        restrict -6 default kod nomodify notrap nopeer noquery
        restrict 127.0.0.1
        restrict -6 ::1
        server ntp.sun.ac.za iburst
        driftfile /var/lib/ntp/drift
